# Generated by Django 4.0.5 on 2022-06-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('menu', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'my_category',
            },
        ),
        migrations.CreateModel(
            name='DrinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nutrition', models.CharField(default='', max_length=256)),
                ('allergy', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categorymodel')),
            ],
            options={
                'db_table': 'my_drink',
            },
        ),
    ]
